openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  /test:
    get:
      tags:
        - Test
      summary: Test 
      description: |
        **REQUIRED PERMISSIONS:** test:read
      responses:
        200:
          description: Returns a test 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
  
  schemas:
    TestResponse:
      type: object
      properties:
        hello:
          type: string  
          example: World
      


